import 'package:flutter/material.dart';
import 'data/models/meal.dart';

List<Meal> DUMMY_MEALS = [
  Meal(title: 'Гавайи',
       subType: 'Салаты',
      typeMeal: 'Европейская',
      ingriedent: [
        'Куриная грудка',
        'черри',
        'свежая зелень',
        "маринованные вешенки",
        "кукуруза",
        "чеснок"
      ],
      description: '',
      cost:32000,
      imageUrl: 'assets/images/gavai.png'),
  Meal(title: 'Гавайи',
      subType: 'Салаты',
      typeMeal: 'Европейская',
      ingriedent: [
        'Куриная грудка',
        'черри',
        'свежая зелень',
        "маринованные вешенки",
        "кукуруза",
        "чеснок"
      ],
      description: '',
      cost:32000,
      imageUrl: 'assets/images/gavai.png'),
  Meal(title: 'Гавайи',
      subType: 'Салаты',
      typeMeal: 'Европейская',
      ingriedent: [
        'Куриная грудка',
        'черри',
        'свежая зелень',
        "маринованные вешенки",
        "кукуруза",
        "чеснок"
      ],
      description: '',
      cost:32000,
      imageUrl: 'assets/images/gavai.png'),
  Meal(title: 'Гавайи',
      subType: 'Салаты',
      typeMeal: 'Европейская',
      ingriedent: [
        'Куриная грудка',
        'черри',
        'свежая зелень',
        "маринованные вешенки",
        "кукуруза",
        "чеснок"
      ],
      description: '',
      cost:32000,
      imageUrl: 'assets/images/gavai.png'),
  Meal(title: 'Гавайи',
      subType: 'Салаты',
      typeMeal: 'Европейская',
      ingriedent: [
        'Куриная грудка',
        'черри',
        'свежая зелень',
        "маринованные вешенки",
        "кукуруза",
        "чеснок"
      ],
      description: '',
      cost:32000,
      imageUrl: 'assets/images/gavai.png'),
  Meal(title: 'Гавайи',
      subType: 'Салаты',
      typeMeal: 'Европейская',
      ingriedent: [
        'Куриная грудка',
        'черри',
        'свежая зелень',
        "маринованные вешенки",
        "кукуруза",
        "чеснок"
      ],
      description: '',
      cost:32000,
      imageUrl: 'assets/images/gavai.png'),
  Meal(title: 'Гавайи',
      subType: 'Салаты',
      typeMeal: 'Европейская',
      ingriedent: [
        'Куриная грудка',
        'черри',
        'свежая зелень',
        "маринованные вешенки",
        "кукуруза",
        "чеснок"
      ],
      description: '',
      cost:32000,
      imageUrl: 'assets/images/gavai.png'),
  Meal(title: 'Гавайи',
      subType: 'Салаты',
      typeMeal: 'Европейская',
      ingriedent: [
        'Куриная грудка',
        'черри',
        'свежая зелень',
        "маринованные вешенки",
        "кукуруза",
        "чеснок"
      ],
      description: '',
      cost:32000,
      imageUrl: 'assets/images/gavai.png'),
  Meal(title: 'Гавайи',
      subType: 'Салаты',
      typeMeal: 'Европейская',
      ingriedent: [
        'Куриная грудка',
        'черри',
        'свежая зелень',
        "маринованные вешенки",
        "кукуруза",
        "чеснок"
      ],
      description: '',
      cost:32000,
      imageUrl: 'assets/images/gavai.png'),
];
List<Color> COLORS=[
  Colors.orange.shade300,
  Colors.deepPurple.shade200,
  Colors.blue.shade200,
  Colors.cyan.shade300,
  Colors.pink.shade200,
  Colors.teal.shade100,
  Colors.indigo.shade200,
];